<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| CSRF Protection
|--------------------------------------------------------------------------
|
| Provides session initialization, CSRF-token generation, form-field
| rendering, token validation, and token rotation.
|
*/

/*
|--------------------------------------------------------------------------
| Secure Session Initialization
|--------------------------------------------------------------------------
*/

function csrfStartSession(): void
{
    if (session_status() === PHP_SESSION_ACTIVE) {
        return;
    }

    session_start([
        'cookie_httponly' => true,
        'cookie_secure' => true,
        'cookie_samesite' => 'Lax',
        'use_strict_mode' => true,
    ]);
}

/*
|--------------------------------------------------------------------------
| Generate or Retrieve CSRF Token
|--------------------------------------------------------------------------
*/

function csrfToken(): string
{
    csrfStartSession();

    $existingToken =
        $_SESSION['csrf_token'] ?? '';

    if (
        is_string($existingToken) &&
        strlen($existingToken) === 64
    ) {
        return $existingToken;
    }

    try {
        $token = bin2hex(
            random_bytes(32)
        );
    } catch (Throwable $exception) {
        error_log(
            'CSRF token generation failed: ' .
            $exception->getMessage()
        );

        throw new RuntimeException(
            'Unable to initialize form security.'
        );
    }

    $_SESSION['csrf_token'] = $token;

    return $token;
}

/*
|--------------------------------------------------------------------------
| Render Hidden CSRF Form Field
|--------------------------------------------------------------------------
|
| The token is generated by the server and escaped before output.
|
*/

function csrfField(): string
{
    return sprintf(
        '<input type="hidden" name="csrf_token" value="%s">',
        e(csrfToken())
    );
}

/*
|--------------------------------------------------------------------------
| Validate Submitted CSRF Token
|--------------------------------------------------------------------------
*/

function csrfIsValid(string $submittedToken): bool
{
    csrfStartSession();

    $storedToken =
        $_SESSION['csrf_token'] ?? '';

    if (
        !is_string($storedToken) ||
        $storedToken === '' ||
        $submittedToken === ''
    ) {
        return false;
    }

    return hash_equals(
        $storedToken,
        $submittedToken
    );
}

/*
|--------------------------------------------------------------------------
| Rotate CSRF Token
|--------------------------------------------------------------------------
|
| The token is removed after a successful submission. A fresh token will
| be generated the next time csrfToken() or csrfField() is called.
|
*/

function csrfRotateToken(): void
{
    csrfStartSession();

    unset(
        $_SESSION['csrf_token']
    );
}